export const TOOL_LABELS = {
  write_scene: "씬 작성 중...",
  read_file: "파일 읽는 중...",
  write_file: "파일 저장 중...",
  check_browser_errors: "에러 확인 중...",
  open_panel: "컨트롤 패널 생성 중...",
  close_panel: "패널 닫는 중...",
  capture_viewport: "화면 캡처 중...",
  search_code: "코드 검색 중...",
  enable_audio: "오디오 설정 중...",
  disable_audio: "오디오 해제 중...",
  enable_mediapipe: "카메라 설정 중...",
  disable_mediapipe: "카메라 해제 중...",
  run_debug_diagnosis: "디버그 분석 중...",
  ask_user: "질문 준비 중...",
  list_files: "파일 목록 조회 중...",
  list_uploaded_files: "업로드 파일 조회 중...",
  start_recording: "녹화 시작 중...",
  generate_wav: "오디오 생성 중...",
  debug_eval: "코드 실행 중...",
};
